#
# This file belongs to MTYPE13 package by Wlodek Bzyl <matwb@univ.gda.pl>
#

DVIPSFLAGS = -u +mobi-000.map

# Read in font independent definitions.

make_root = ../../../make
include $(make_root)/type3common.mk

mobi-000.dvi : mobi-000.t3 mobi-000.proof
