#
# METATYPE 1 PACKAGE                    Wlodek Bzyl <matwb@univ.gda.pl>
#

# Read in font independent definitions.

include ../make/common.mk

FONTS = redis-p

MKPROOF1OPT = -fmt=mex -translate-file=il2-pl -u +redis-p.map
