#
# This file belongs to MTYPE13 package by Wlodek Bzyl <matwb@univ.gda.pl>
#

MKPROOF1OPT = --translate-file=il2-pl --fmt=mex

# Read in font independent definitions.

make_root = ../../../make
include $(make_root)/type1common.mk

tapes.dvi : tapes.pfb tapes.proof
