#
# This file belongs to MTYPE13 package by Wlodek Bzyl <matwb@univ.gda.pl>
#

FONTS = plus

#MKPROOF1OPT = -u plus.map

# Read in font independent definitions.

make_root = ../../../make
include $(make_root)/type1common.mk

plus.ps : plus.mp
