#
# This file belongs to MTYPE13 package by Wlodek Bzyl <matwb@univ.gda.pl>
#

DVIPSFLAGS = -u +sign-000.map

# Read in font independent definitions.

make_root = ../../../make
include $(make_root)/type3common.mk

GENERATEDFILES = test-signs.{log,dvi,ps}

sign-000.dvi : sign-000.t3 sign-000.proof

test-signs.dvi : sign-000.t3
